version: '3'
services:
  mysql:
    image: 'mysql/mysql-server'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kysely_test
    ports:
      - '3308:3306'
    volumes:
      - ./test/scripts/mysql-init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_DB: kysely_test
      POSTGRES_USER: kysely
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5434:5432'
  cockroachdb:
    image: cockroachdb/cockroach
    command: start-single-node --insecure
    environment:
      COCKROACH_DATABASE: kysely_test
      COCKROACH_USER: kysely
    ports:
      - '26257:26257'
